[2024-08-21T06:27:32.527+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-21T06:27:32.638+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_22024-08-21.validate_the_api scheduled__2024-08-06T00:00:00+00:00 [queued]>
[2024-08-21T06:27:32.684+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_22024-08-21.validate_the_api scheduled__2024-08-06T00:00:00+00:00 [queued]>
[2024-08-21T06:27:32.687+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-21T06:27:32.781+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): validate_the_api> on 2024-08-06 00:00:00+00:00
[2024-08-21T06:27:32.798+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4407) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T06:27:32.798+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_22024-08-21', 'validate_the_api', 'scheduled__2024-08-06T00:00:00+00:00', '--job-id', '726', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmpz4z077qn']
[2024-08-21T06:27:32.803+0000] {standard_task_runner.py:91} INFO - Job 726: Subtask validate_the_api
[2024-08-21T06:27:32.802+0000] {standard_task_runner.py:63} INFO - Started process 4416 to run task
[2024-08-21T06:27:33.023+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_22024-08-21.validate_the_api scheduled__2024-08-06T00:00:00+00:00 [running]> on host 7e1333882d71
[2024-08-21T06:27:33.326+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_22024-08-21' AIRFLOW_CTX_TASK_ID='validate_the_api' AIRFLOW_CTX_EXECUTION_DATE='2024-08-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-06T00:00:00+00:00'
[2024-08-21T06:27:33.331+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-21T06:27:33.400+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T06:27:33.409+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/api_utils.py']
[2024-08-21T06:27:33.424+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T06:27:34.802+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-21T06:27:34.812+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-21T06:27:35.056+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_22024-08-21, task_id=validate_the_api, run_id=scheduled__2024-08-06T00:00:00+00:00, execution_date=20240806T000000, start_date=20240821T062732, end_date=20240821T062735
[2024-08-21T06:27:35.611+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-21T06:27:35.797+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
