[2024-08-21T06:01:23.123+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-21T06:01:23.213+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mega2024-08-21.decrypt_the_data scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-08-21T06:01:23.258+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mega2024-08-21.decrypt_the_data scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-08-21T06:01:23.268+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-21T06:01:23.317+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): decrypt_the_data> on 2024-05-14 00:00:00+00:00
[2024-08-21T06:01:23.340+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=397) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T06:01:23.343+0000] {standard_task_runner.py:63} INFO - Started process 408 to run task
[2024-08-21T06:01:23.338+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_mega2024-08-21', 'decrypt_the_data', 'scheduled__2024-05-14T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmpancvzuel']
[2024-08-21T06:01:23.353+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask decrypt_the_data
[2024-08-21T06:01:23.645+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_mega2024-08-21.decrypt_the_data scheduled__2024-05-14T00:00:00+00:00 [running]> on host 7e1333882d71
[2024-08-21T06:01:24.079+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_mega2024-08-21' AIRFLOW_CTX_TASK_ID='decrypt_the_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-14T00:00:00+00:00'
[2024-08-21T06:01:24.083+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-21T06:01:24.119+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T06:01:24.128+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/decryption_utils.py']
[2024-08-21T06:01:24.186+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T06:01:24.595+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-21T06:01:24.599+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-21T06:01:24.693+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_mega2024-08-21, task_id=decrypt_the_data, run_id=scheduled__2024-05-14T00:00:00+00:00, execution_date=20240514T000000, start_date=20240821T060123, end_date=20240821T060124
[2024-08-21T06:01:24.764+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-21T06:01:24.836+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-21T06:01:24.848+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
