[2024-08-21T06:01:25.956+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-21T06:01:26.049+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mega2024-08-21.decrypt_the_data scheduled__2024-05-19T00:00:00+00:00 [queued]>
[2024-08-21T06:01:26.105+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mega2024-08-21.decrypt_the_data scheduled__2024-05-19T00:00:00+00:00 [queued]>
[2024-08-21T06:01:26.107+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-21T06:01:26.172+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): decrypt_the_data> on 2024-05-19 00:00:00+00:00
[2024-08-21T06:01:26.197+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=436) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T06:01:26.198+0000] {standard_task_runner.py:63} INFO - Started process 455 to run task
[2024-08-21T06:01:26.195+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_mega2024-08-21', 'decrypt_the_data', 'scheduled__2024-05-19T00:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmp8ioljrhs']
[2024-08-21T06:01:26.203+0000] {standard_task_runner.py:91} INFO - Job 71: Subtask decrypt_the_data
[2024-08-21T06:01:26.385+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_mega2024-08-21.decrypt_the_data scheduled__2024-05-19T00:00:00+00:00 [running]> on host 7e1333882d71
[2024-08-21T06:01:26.576+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_mega2024-08-21' AIRFLOW_CTX_TASK_ID='decrypt_the_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-19T00:00:00+00:00'
[2024-08-21T06:01:26.576+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-21T06:01:26.607+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T06:01:26.623+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/decryption_utils.py']
[2024-08-21T06:01:26.647+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T06:01:26.947+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-21T06:01:26.949+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-21T06:01:27.069+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_mega2024-08-21, task_id=decrypt_the_data, run_id=scheduled__2024-05-19T00:00:00+00:00, execution_date=20240519T000000, start_date=20240821T060126, end_date=20240821T060127
[2024-08-21T06:01:27.171+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-21T06:01:27.234+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
