[2024-08-07T10:43:41.772+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T10:43:41.824+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_2024-08-07.validate_the_data scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-08-07T10:43:41.831+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_2024-08-07.validate_the_data scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-08-07T10:43:41.831+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-07T10:43:41.900+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): validate_the_data> on 2024-05-11 00:00:00+00:00
[2024-08-07T10:43:41.905+0000] {standard_task_runner.py:63} INFO - Started process 1877 to run task
[2024-08-07T10:43:41.919+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_2024-08-07', 'validate_the_data', 'scheduled__2024-05-11T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmpbl72xf_p']
[2024-08-07T10:43:41.922+0000] {standard_task_runner.py:91} INFO - Job 155: Subtask validate_the_data
[2024-08-07T10:43:42.014+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_2024-08-07.validate_the_data scheduled__2024-05-11T00:00:00+00:00 [running]> on host 8cffaad11d99
[2024-08-07T10:43:42.162+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_2024-08-07' AIRFLOW_CTX_TASK_ID='validate_the_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-11T00:00:00+00:00'
[2024-08-07T10:43:42.167+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T10:43:42.194+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-07T10:43:42.195+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/validation_utils.py']
[2024-08-07T10:43:42.203+0000] {subprocess.py:86} INFO - Output:
[2024-08-07T10:43:42.440+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-07T10:43:42.441+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T10:43:42.480+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_2024-08-07, task_id=validate_the_data, run_id=scheduled__2024-05-11T00:00:00+00:00, execution_date=20240511T000000, start_date=20240807T104341, end_date=20240807T104342
[2024-08-07T10:43:42.564+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-07T10:43:42.573+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-07T10:49:49.229+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T10:49:49.252+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_2024-08-07.validate_the_data scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-08-07T10:49:49.259+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_2024-08-07.validate_the_data scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-08-07T10:49:49.260+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-07T10:49:50.070+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): validate_the_data> on 2024-05-11 00:00:00+00:00
[2024-08-07T10:49:50.074+0000] {standard_task_runner.py:63} INFO - Started process 2673 to run task
[2024-08-07T10:49:50.077+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_2024-08-07', 'validate_the_data', 'scheduled__2024-05-11T00:00:00+00:00', '--job-id', '371', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmpbdg9kevz']
[2024-08-07T10:49:50.080+0000] {standard_task_runner.py:91} INFO - Job 371: Subtask validate_the_data
[2024-08-07T10:49:50.184+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_2024-08-07.validate_the_data scheduled__2024-05-11T00:00:00+00:00 [running]> on host 8cffaad11d99
[2024-08-07T10:49:50.312+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_2024-08-07' AIRFLOW_CTX_TASK_ID='validate_the_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-11T00:00:00+00:00'
[2024-08-07T10:49:50.313+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T10:49:50.325+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-07T10:49:50.325+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/validation_utils.py']
[2024-08-07T10:49:50.331+0000] {subprocess.py:86} INFO - Output:
[2024-08-07T10:49:50.566+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-07T10:49:50.567+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T10:49:50.785+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_2024-08-07, task_id=validate_the_data, run_id=scheduled__2024-05-11T00:00:00+00:00, execution_date=20240511T000000, start_date=20240807T104949, end_date=20240807T104950
[2024-08-07T10:49:50.849+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-07T10:49:50.862+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-07T10:49:50.897+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
