[2024-08-09T09:28:05.549+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-09T09:28:05.577+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_2024-08-09.validate_the_data scheduled__2024-07-29T00:00:00+00:00 [queued]>
[2024-08-09T09:28:05.583+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_2024-08-09.validate_the_data scheduled__2024-07-29T00:00:00+00:00 [queued]>
[2024-08-09T09:28:05.583+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-09T09:28:05.658+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): validate_the_data> on 2024-07-29 00:00:00+00:00
[2024-08-09T09:28:05.662+0000] {standard_task_runner.py:63} INFO - Started process 12646 to run task
[2024-08-09T09:28:05.666+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_2024-08-09', 'validate_the_data', 'scheduled__2024-07-29T00:00:00+00:00', '--job-id', '2302', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmp7hbrjt_x']
[2024-08-09T09:28:05.668+0000] {standard_task_runner.py:91} INFO - Job 2302: Subtask validate_the_data
[2024-08-09T09:28:05.730+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_2024-08-09.validate_the_data scheduled__2024-07-29T00:00:00+00:00 [running]> on host 05bc191a9412
[2024-08-09T09:28:05.867+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_2024-08-09' AIRFLOW_CTX_TASK_ID='validate_the_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-29T00:00:00+00:00'
[2024-08-09T09:28:05.868+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-09T09:28:05.880+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-09T09:28:05.881+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/validation_utils.py']
[2024-08-09T09:28:05.887+0000] {subprocess.py:86} INFO - Output:
[2024-08-09T09:28:06.151+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-09T09:28:06.152+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-09T09:28:06.227+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_2024-08-09, task_id=validate_the_data, run_id=scheduled__2024-07-29T00:00:00+00:00, execution_date=20240729T000000, start_date=20240809T092805, end_date=20240809T092806
[2024-08-09T09:28:06.319+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-09T09:28:06.333+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-09T09:28:06.346+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
