[2024-08-21T06:27:42.099+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-21T06:27:42.203+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_22024-08-21.validate_the_data scheduled__2024-08-08T00:00:00+00:00 [queued]>
[2024-08-21T06:27:42.226+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_22024-08-21.validate_the_data scheduled__2024-08-08T00:00:00+00:00 [queued]>
[2024-08-21T06:27:42.227+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-21T06:27:42.276+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): validate_the_data> on 2024-08-08 00:00:00+00:00
[2024-08-21T06:27:42.312+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_22024-08-21', 'validate_the_data', 'scheduled__2024-08-08T00:00:00+00:00', '--job-id', '757', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmp902t97uq']
[2024-08-21T06:27:42.316+0000] {standard_task_runner.py:91} INFO - Job 757: Subtask validate_the_data
[2024-08-21T06:27:42.314+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4501) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T06:27:42.323+0000] {standard_task_runner.py:63} INFO - Started process 4512 to run task
[2024-08-21T06:27:42.456+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_22024-08-21.validate_the_data scheduled__2024-08-08T00:00:00+00:00 [running]> on host 7e1333882d71
[2024-08-21T06:27:42.591+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_22024-08-21' AIRFLOW_CTX_TASK_ID='validate_the_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-08T00:00:00+00:00'
[2024-08-21T06:27:42.592+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-21T06:27:42.612+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T06:27:42.614+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/validation_utils.py']
[2024-08-21T06:27:42.627+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T06:27:43.525+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-21T06:27:43.535+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-21T06:27:43.690+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_22024-08-21, task_id=validate_the_data, run_id=scheduled__2024-08-08T00:00:00+00:00, execution_date=20240808T000000, start_date=20240821T062742, end_date=20240821T062743
[2024-08-21T06:27:43.777+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-21T06:27:43.946+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-21T06:27:43.965+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
