[2024-08-21T06:26:59.255+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-21T06:26:59.421+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_22024-08-21.final_etl_processing scheduled__2024-07-22T00:00:00+00:00 [queued]>
[2024-08-21T06:26:59.514+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_22024-08-21.final_etl_processing scheduled__2024-07-22T00:00:00+00:00 [queued]>
[2024-08-21T06:26:59.537+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-21T06:26:59.854+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): final_etl_processing> on 2024-07-22 00:00:00+00:00
[2024-08-21T06:26:59.940+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4227) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T06:26:59.955+0000] {standard_task_runner.py:63} INFO - Started process 4253 to run task
[2024-08-21T06:26:59.939+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_22024-08-21', 'final_etl_processing', 'scheduled__2024-07-22T00:00:00+00:00', '--job-id', '702', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmpy9tigh3t']
[2024-08-21T06:26:59.974+0000] {standard_task_runner.py:91} INFO - Job 702: Subtask final_etl_processing
[2024-08-21T06:27:00.433+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_22024-08-21.final_etl_processing scheduled__2024-07-22T00:00:00+00:00 [running]> on host 7e1333882d71
[2024-08-21T06:27:01.224+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_22024-08-21' AIRFLOW_CTX_TASK_ID='final_etl_processing' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-22T00:00:00+00:00'
[2024-08-21T06:27:01.234+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-21T06:27:01.344+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T06:27:01.352+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "python3 /opt/***/data/etl_m12.py --connection postgresql+psycopg2://***:***@postgres/postgres --csv ''"]
[2024-08-21T06:27:01.423+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T06:27:11.431+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-21T06:27:11.442+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-21T06:27:11.724+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_22024-08-21, task_id=final_etl_processing, run_id=scheduled__2024-07-22T00:00:00+00:00, execution_date=20240722T000000, start_date=20240821T062659, end_date=20240821T062711
[2024-08-21T06:27:11.963+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-21T06:27:12.286+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-21T06:27:12.303+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
