[2024-08-21T06:27:33.760+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-21T06:27:33.883+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_22024-08-21.validate_the_api scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-21T06:27:33.894+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_22024-08-21.validate_the_api scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-21T06:27:33.899+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-21T06:27:34.000+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): validate_the_api> on 2024-08-12 00:00:00+00:00
[2024-08-21T06:27:34.027+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4424) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T06:27:34.037+0000] {standard_task_runner.py:63} INFO - Started process 4432 to run task
[2024-08-21T06:27:34.035+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_22024-08-21', 'validate_the_api', 'scheduled__2024-08-12T00:00:00+00:00', '--job-id', '731', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmpvnoalool']
[2024-08-21T06:27:34.055+0000] {standard_task_runner.py:91} INFO - Job 731: Subtask validate_the_api
[2024-08-21T06:27:34.349+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_22024-08-21.validate_the_api scheduled__2024-08-12T00:00:00+00:00 [running]> on host 7e1333882d71
[2024-08-21T06:27:34.559+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_22024-08-21' AIRFLOW_CTX_TASK_ID='validate_the_api' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-12T00:00:00+00:00'
[2024-08-21T06:27:34.561+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-21T06:27:34.579+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T06:27:34.581+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/api_utils.py']
[2024-08-21T06:27:34.598+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T06:27:35.989+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-21T06:27:35.999+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-21T06:27:36.231+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_22024-08-21, task_id=validate_the_api, run_id=scheduled__2024-08-12T00:00:00+00:00, execution_date=20240812T000000, start_date=20240821T062733, end_date=20240821T062736
[2024-08-21T06:27:36.438+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-21T06:27:36.565+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-21T06:27:36.577+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
